[package]
name = "rlua-eval-example"
version = "0.1.0"
authors = ["Richard Cook <rcook@rcook.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = "0.17.0"
